version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test
      - store_artifacts:
          path: test
          destination: junit

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
